apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: step-ca-issuer
  namespace: cert-manager
spec:
  acme:
    preferredChain: ""
    privateKeySecretRef:
      name: step-ca-issuer-key
    server: https://step-certificates.step.svc.cluster.local/acme/acme/directory
    skipTLSVerify: true
    solvers:
    - http01:
        ingress:
          serviceType: ClusterIP

